name: Cloth Store CI Pipeline

on:
 push:
  branches: [ main ]

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v3

   - name: List files
     run: ls

   - name: Pipeline success
     run: echo "Cloth store CI pipeline successful!"
